login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres

development:
  adapter: postgresql
  database: OwlCabinet_dev
  pool: 5
  <<: *login

test:
  adapter: postgresql
  database: OwlCabinet_test
  pool: 5
  <<: *login

production:
  adapter: postgresql
  database: OwlCabinet_production
  pool: 5
  <<: *login
